TuneTown/Controllers/InfoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TuneTown.Models;
using TuneTown.Repo;

namespace TuneTown.Controllers
{
    public class InfoController : Controller
    {
        #region TODO
        //Required
        // Do load testing

        //Optional
        // Implement a way to select filters from one box (html dropdown)
            // possibly a new property in submissions? - ask brian
        // Style the page
        #endregion

        #region Initialization
        ISubmissionRepository SubmissionRepository { get; set; }
        readonly UserManager<AppUser> userManager; //revert this if readonly causes issues
        public InfoController(ISubmissionRepository submissionRepository, UserManager<AppUser> userManager)
        {
            SubmissionRepository = submissionRepository;
            this.userManager = userManager;
        }
        #endregion

        #region Info Views and Filter Methods
        #region Index (Info)
        public async Task<IActionResult> Index(string userName, string dateSubmitted)
        {
            List<Submission> submissions;
            if (userName != null)
            {
                submissions = await(
                   from s in SubmissionRepository.Submissions
                   where s.User.UserName == userName
                   select s
                   ).ToListAsync<Submission>();
            }
            else if (dateSubmitted != null)
            {
                submissions = await (
                  from s in SubmissionRepository.Submissions
                  where s.DateSubmitted == DateOnly.FromDateTime(DateTime.Parse(dateSubmitted))
                  select s
                  ).ToListAsync<Submission>();
            }
            else
            {
                submissions = await SubmissionRepository.Submissions.ToListAsync<Submission>();
            }

            return View(submissions);
        }
        #endregion

        #region Albums
        public async Task<IActionResult> Albums(string albumName, string groupName, string releaseDate, int trackTotal, string labelName)
        {
            List<Submission> submissions;
            if (albumName != null)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Album.AlbumName == albumName
                   select s
                   ).ToListAsync<Submission>();
            }
            else if (groupName != null)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Album.GroupName == groupName
                   select s
                   ).ToListAsync<Submission>();
            }
            else if (releaseDate != null)
            {
                submissions = await (
                  from s in SubmissionRepository.Submissions
                  where s.Song.Album.ReleaseDate == DateTime.Parse(releaseDate)
                  select s
                  ).ToListAsync<Submission>();
            }
            else if (trackTotal > 0)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Album.TrackTotal == trackTotal
                   select s
                   ).ToListAsync<Submission>();
            }
            else if (labelName != null)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Album.LabelName == labelName
                   select s
                   ).ToListAsync<Submission>();
            }
            else
            {
                submissions = await SubmissionRepository.Submissions.ToListAsync<Submission>();
            }

            return View(submissions);
        }
        #endregion

        #region Artists
        public async Task<IActionResult> Artists(string publicAlias, string firstName, string lastName, string affiliatedLabel)
        {
            List<Submission> submissions;
            if (publicAlias != null)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Artist.PublicAlias == publicAlias
                   select s
                   ).ToListAsync<Submission>();
            }
            else if (firstName != null)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Artist.FirstName == firstName
                   select s
                   ).ToListAsync<Submission>();
            }
            else if (lastName != null)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Artist.LastName == lastName
                   select s
                   ).ToListAsync<Submission>();
            }
            else if (affiliatedLabel != null)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.Artist.AffiliatedLabels.Contains(affiliatedLabel)
                   select s
                   ).ToListAsync<Submission>();
            }
            else
            {
                submissions = await SubmissionRepository.Submissions.ToListAsync<Submission>();
            }

            return View(submissions);
        }
        #endregion

        #region Songs
        public async Task<IActionResult> Songs(string releaseDate, int bitRate)
        {
            List<Submission> submissions;
            if (releaseDate != null)
            {
                submissions = await (
                  from s in SubmissionRepository.Submissions
                  where s.Song.ReleaseDate == DateTime.Parse(releaseDate)
                  select s
                  ).ToListAsync<Submission>();
            }
            else if (bitRate > 0)
            {
                submissions = await (
                   from s in SubmissionRepository.Submissions
                   where s.Song.BitRate >= bitRate
                   select s
                   ).ToListAsync<Submission>();
            }
            else
            {
                submissions = await SubmissionRepository.Submissions.ToListAsync<Submission>();
            }

            return View(submissions);
        }
        #endregion
        #endregion

        #region Submission View and Post Methods
        [Authorize(Roles = "Admin,Poster")]
        public IActionResult Submission()
        {
            return View();
        }

        [Authorize(Roles = "Admin,Poster")]
        [HttpPost]
        public async Task<IActionResult> Submission(Submission model)
        {
            if (userManager != null)
            {
                model.User = await userManager.GetUserAsync(User);
            }
            
            if (await SubmissionRepository.CreateSubmissionAsync(model) > 0)
            {
                return RedirectToAction("Index", new { submissionId = model.SubmissionId });
            }
            else
                return View();
        }
        #endregion
    }
}

TuneTown/Controllers/PlaybackController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TuneTown.Data;
using TuneTown.Models;
using TuneTown.Repo;

namespace TuneTown.Controllers
{
    public class PlaybackController : Controller
    {
        #region Initialization
        private ISubmissionRepository SubmissionRepository { get; set; }
        UserManager<AppUser> userManager;
        public PlaybackController(ISubmissionRepository s, UserManager<AppUser> userMngr)
        {
            SubmissionRepository = s;
            userManager = userMngr;
        }
        #endregion

        #region View
        public async Task<IActionResult> Index()
        {
            //add the if else just in case this is ever null
            return View(await SubmissionRepository.Submissions.ToListAsync<Submission>());
        }
        #endregion

        #region Comments
        // The issue I'm having is that the songid is getting set to 0 and im unsure how the value is getting passed into it
        [Authorize]
        public IActionResult Comment(int songId)
        {
            var commentVM = new CommentVM { SongId = songId };
            return View(commentVM);
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Comment(CommentVM commentVM)
        {
            var comment = new Comment { CommentText = commentVM.CommentText };
            comment.Commenter = userManager.GetUserAsync(User).Result;
            comment.PostDate = DateTime.Now;

            /*var submission = (from s in SubmissionRepository.Submissions
                                .Include(s => s.Song.Comments)
                                .ThenInclude(c => c.Commenter)
                              where s.Song.SongId == commentVM.SongId
                              select s).First<Submission>();*/
            var submission = (from s in SubmissionRepository.Submissions
                              where s.Song.SongId == commentVM.SongId
                              select s).First<Submission>();

            submission.Song.Comments.Add(comment);
            await SubmissionRepository.UpdateSubmissionAsync(submission);

            return RedirectToAction("Index");
        }
        #endregion
    }
}

TuneTown/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TuneTown.Models;
using TuneTown.Repo;
using System.Data;

namespace TuneTown.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private UserManager<AppUser> userManager;
        private RoleManager<IdentityRole> roleManager;
        private ISubmissionRepository submissionRepo;

        public UserController(UserManager<AppUser> userMngr,
                               RoleManager<IdentityRole> roleMngr,
                               ISubmissionRepository repo)
        {
            userManager = userMngr;
            roleManager = roleMngr;
            submissionRepo = repo;
        }

        /// Get a list of all users. Each user will have a list of their
        public async Task<IActionResult> Index()
        {
            List<AppUser> users = new List<AppUser>();
            foreach (AppUser user in userManager.Users)
            {
                user.RoleNames = await userManager.GetRolesAsync(user);
                users.Add(user);
            }

            UserVM model = new UserVM
            {
                Users = users, // List of AppUsers
                Roles = roleManager.Roles
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (!result.Succeeded)
                { // if failed
                    string errorMessage = "";
                    foreach (IdentityError error in result.Errors)
                    {
                        errorMessage += error.Description + " | ";
                    }
                    TempData["message"] = errorMessage;
                }
            }
            return RedirectToAction("Index");
        }

        #region Role Addition
        [HttpPost]
        public async Task<IActionResult> AddToAdmin(string id)
        {
            IdentityRole adminRole = await roleManager.FindByNameAsync("Admin");
            if (adminRole == null)
            {
                TempData["message"] = "Admin role does not exist. "
                + "Click 'Create Admin Role' button to create it.";
            }
            else
            {
                AppUser user = await userManager.FindByIdAsync(id);
                await userManager.AddToRoleAsync(user, adminRole.Name);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddToPoster(string id)
        {
            IdentityRole posteRole = await roleManager.FindByNameAsync("Poster");
            if (posteRole == null)
            {
                TempData["message"] = "Poster role does not exist. "
                + "Click 'Create Poster Role' button to create it.";
            }
            else
            {
                AppUser user = await userManager.FindByIdAsync(id);
                await userManager.AddToRoleAsync(user, posteRole.Name);
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region Role Removal
        [HttpPost]
        public async Task<IActionResult> RemoveFromAdmin(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            await userManager.RemoveFromRoleAsync(user, "Admin");
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveFromPoster(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            await userManager.RemoveFromRoleAsync(user, "Poster");
            return RedirectToAction("Index");
        }
        #endregion

        #region Role Deletion
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            await roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }
        #endregion

        #region Role Creation
        [HttpPost]
        public async Task<IActionResult> CreateAdminRole()
        {
            await roleManager.CreateAsync(new IdentityRole("Admin"));
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> CreatePosterRole()
        {
            await roleManager.CreateAsync(new IdentityRole("Poster"));
            return RedirectToAction("Index");
        }
        #endregion

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(RegisterVM model)
        {

            if (ModelState.IsValid)
            {
                var user = new AppUser { UserName = model.Username };
                var result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }
    }
}

TuneTown/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TuneTown</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TuneTown.styles.css" asp-append-version="true" />
</head>

@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> signInManager

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TuneTown</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <!--Navbar Links-->
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Index">Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Artists">Artists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Albums">Albums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Songs">Songs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Playback" asp-action="Index">Playback</a>
                        </li>
                        @if (User.IsInRole("Poster"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Submission">Submit</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Admin</a>
                            </li>
                        }
                    </ul>

                    <!--Navbar User Stuff-->
                    <ul class="navbar-nav ms-auto">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark asp-controller="User" asp-action="Index">&nbsp;Admin</a>
                            </li>
                        }
                        @if (signInManager.IsSignedIn(User))
                        {
                        //sign in, log out, username
                            <li class="nav-item bg-prim">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <input type="submit" value="Log Out" class="btn btn-outline-dark btn-light" />
                                    <span class="text-dark">@User.Identity.Name</span>
                                </form>
                            </li>
                        }
                        else
                        {
                            //get current action
                            var action = ViewContext.RouteData.Values["action"]?.ToString();
                            //register, sign in
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">
                                    <span class="fas fa-edit"></span> &nbsp; Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Login" asp-controller="Account" class="btn btn-outline-dark">Log In</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TuneTown - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>